version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/packages/hidp'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase-if-necessary

  - package-ecosystem: 'pip'
    directory: '/project'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase-if-necessary

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
