version: 2
updates:
  - package-ecosystem: pip
    directories:
      - '/packages/hidp'
      - '/project'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase-if-necessary

  - package-ecosystem: 'github-actions'
    directories:
      - '/.github/actions/*'
      - '/.github/workflows'
    schedule:
      interval: 'weekly'
