name: Backend
description: Lint, checks & tests

inputs:
  working-directory:
    description: 'The working directory to run the commands in'

runs:
  using: composite

  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      run: |
        python -m pip install --root-user-action=ignore -U uv
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Install dependencies
      run: |
        uv venv ./var/venv
        source ./var/venv/bin/activate
        make install-pipeline
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Lint
      run: |
        source ./var/venv/bin/activate
        make lint
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        RUFF_OUTPUT_FORMAT: github

    - name: Django checks
      run: |
        source ./var/venv/bin/activate
        make django-checks
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Django migration checks
      run: |
        source ./var/venv/bin/activate
        make migrationtest
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Tests
      run: |
        source ./var/venv/bin/activate
        make coveragetest
      working-directory: ${{ inputs.working-directory }}
      shell: bash
