name: Setup Python
description: Setup Python and install dependencies

inputs:
  working-directory:
    description: The working directory to run the commands in

runs:
  using: composite

  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install system packages (gettext)
      run: |
        echo ::group::System setup
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gettext
        echo ::endgroup::
      shell: bash

    - name: Install uv
      run: |
        echo ::group::Install uv
        python -m pip install --root-user-action=ignore -U uv
        echo ::endgroup::
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Install dependencies
      run: |
        echo ::group::Create/activate virtualenv
        uv venv ~/.venv
        source ~/.venv/bin/activate
        echo ::endgroup::
        make install-pipeline
      working-directory: ${{ inputs.working-directory }}
      shell: bash
