name: Setup Python
description: Setup Python and install dependencies

inputs:
  working-directory:
    description: The working directory to run the commands in

runs:
  using: composite

  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      run: |
        python -m pip install --root-user-action=ignore -U uv
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Install dependencies
      run: |
        uv venv ./var/venv
        source ./var/venv/bin/activate
        make install-pipeline
      working-directory: ${{ inputs.working-directory }}
      shell: bash
