name: Setup Python
description: Setup Python and install dependencies

inputs:
  working-directory:
    description: The working directory to run the commands in
  python-version:
    description: The Python version to use
  django-version:
    description: The Django version to use as dependency

runs:
  using: composite

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}
        activate-environment: true
        enable-cache: true

    - name: Install system packages (gettext)
      run: |
        echo ::group::System setup
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gettext
        echo ::endgroup::
      shell: bash

    - name: Set Django version
      run: |
        echo ::group::Set Django version environment variable
        echo "DJANGO_VERSION=${{ inputs.django-version }}" >> $GITHUB_ENV
        echo ::endgroup::
      shell: bash

    - name: Install dependencies
      run: |
        make install-pipeline
      working-directory: ${{ inputs.working-directory }}
      shell: bash
