name: Build HIdP Documentation
description: Build the documentation for the HIdP package

runs:
  using: composite

  steps:
    - name: Setup Python
      uses: ./.github/actions/setup-python
      with:
        working-directory: './packages/hidp'
        python-version: '3.13'
        django-version: '5.2'

    - name: Build documentation
      run: |
        echo ::group::Build documentation
        make html
        echo ::endgroup::
      working-directory: './packages/hidp/docs'
      shell: bash
