name: Build Documentation

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python
        with:
          working-directory: './packages/hidp'

      - name: Build documentation
        run: |
          source ./var/venv/bin/activate
          make html
        working-directory: './packages/hidp/docs'
        shell: bash
