name: Build Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          python -m pip install --root-user-action=ignore -U uv
        shell: bash

      - name: Install dependencies
        run: |
          uv venv ./var/venv
          source ./var/venv/bin/activate
          uv pip install -r requirements.txt
        working-directory: './packages/hidp/docs'
        shell: bash

      - name: Build documentation
        run: |
          source ./var/venv/bin/activate
          make html
        working-directory: './packages/hidp/docs'
        shell: bash
        env:
          RUFF_OUTPUT_FORMAT: github

